SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE

CURSOR C_EMPLOYEE_LIST IS
    SELECT SALARY
      FROM EMPLOYEE;

V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &SV_EMPLOYEE_ID;
V_SALARY EMPLOYEE.SALARY%TYPE;

BEGIN
    OPEN C_EMPLOYEE_LIST;
        LOOP
            FETCH C_EMPLOYEE_LIST INTO V_SALARY;
            EXIT WHEN C_EMPLOYEE_LIST%NOTFOUND;

            IF MOD(V_SALARY,2) = 0 THEN
                DBMS_OUTPUT.PUT_LINE(V_SALARY || ' IS EVEN');
            END IF;
          
        END LOOP;
    CLOSE C_EMPLOYEE_LIST;
END;
/