SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    CURSOR C_EMPLOYEE_LIST IS
    SELECT FIRST_NAME, LAST_NAME,SALARY
        FROM EMPLOYEE;

    V_ROW C_EMPLOYEE_LIST%ROWTYPE; 

BEGIN
    OPEN C_EMPLOYEE_LIST;
        LOOP
           FETCH C_EMPLOYEE_LIST INTO V_ROW;
           EXIT WHEN C_EMPLOYEE_LIST%NOTFOUND;
           DBMS_OUTPUT.PUT_LINE('FIRST NAME : ' || V_ROW.FIRST_NAME);
           DBMS_OUTPUT.PUT_LINE('SECOND NAME : ' || V_ROW.LAST_NAME);
           DBMS_OUTPUT.PUT_LINE('SALARY  : ' || V_ROW.SALARY);
           DBMS_OUTPUT.PUT_LINE(CHR(10));
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('COUNT : ' || C_EMPLOYEE_LIST%ROWCOUNT);
    CLOSE C_EMPLOYEE_LIST;
END;
/