SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    CURSOR C_EMPLOYEE_LIST IS
    SELECT FIRST_NAME, LAST_NAME,SALARY
        FROM EMPLOYEE;

    V_FIRST_NAME    EMPLOYEE.FIRST_NAME%TYPE;
    V_LAST_NAME     EMPLOYEE.LAST_NAME%TYPE;
    V_SALARY        EMPLOYEE.SALARY%TYPE;    

BEGIN
    OPEN C_EMPLOYEE_LIST;
        LOOP
           FETCH C_EMPLOYEE_LIST INTO V_FIRST_NAME,V_LAST_NAME,V_SALARY;
           EXIT WHEN C_EMPLOYEE_LIST%NOTFOUND;
           DBMS_OUTPUT.PUT_LINE('FIRST NAME : ' || V_FIRST_NAME);
           DBMS_OUTPUT.PUT_LINE('SECOND NAME : ' || V_LAST_NAME);
           DBMS_OUTPUT.PUT_LINE('SALARY  : ' || V_SALARY);
           DBMS_OUTPUT.PUT_LINE(CHR(10));
        END LOOP;
        DBMS_OUTPUT.PUT_LINE('COUNT : ' || C_EMPLOYEE_LIST%ROWCOUNT);
    CLOSE C_EMPLOYEE_LIST;
END;
/