SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    CURSOR C_SALES IS
        SELECT DISTINCT SALESPERSON_ID 
        FROM CUSTOMER;
    V_SALARY EMPLOYEE.SALARY%TYPE;
BEGIN
    FOR V_ROW IN C_SALES LOOP
        UPDATE EMPLOYEE
            SET SALARY=SALARY * 1.10
            WHERE EMPLOYEE_ID = V_ROW.SALESPERSON_ID;
        SELECT SALARY
            INTO V_SALARY
            FROM EMPLOYEE
        WHERE EMPLOYEE_ID = V_ROW.SALESPERSON_ID;             
        DBMS_OUTPUT.PUT_LINE('SALARY : ' || V_SALARY);
    END LOOP;
END;
/