SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
V_MIN NUMBER;
V_MAX NUMBER;
V_AVG NUMBER;
V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &SV_EMPLOYEE_ID;
V_SALARY EMPLOYEE.SALARY%TYPE;

BEGIN
    SELECT MIN(SALARY), MAX(SALARY), AVG(SALARY)
        INTO V_MIN, V_MAX, V_AVG
        FROM EMPLOYEE;

    SELECT SALARY
        INTO V_SALARY
        FROM EMPLOYEE
        WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
 
        DBMS_OUTPUT.PUT_LINE('MINIMUM SALARY : ' || V_MIN);
        DBMS_OUTPUT.PUT_LINE('AVERAGE SALARY : ' || V_AVG);
        DBMS_OUTPUT.PUT_LINE('MAXIMUM SALARY : ' || V_MAX);

    IF V_SALARY = V_MIN THEN
        DBMS_OUTPUT.PUT_LINE('SALARY OF ' || V_EMPLOYEE_ID || ' IS MINIMUM.');
    ELSIF V_SALARY < V_AVG THEN
        DBMS_OUTPUT.PUT_LINE('SALARY OF ' || V_EMPLOYEE_ID || ' IS LESS THAN AVERAGE.');  
    ELSIF V_SALARY = V_AVG THEN
        DBMS_OUTPUT.PUT_LINE('SALARY OF ' || V_EMPLOYEE_ID || ' IS AVERAGE.');
    ELSIF V_SALARY < V_MAX THEN
        DBMS_OUTPUT.PUT_LINE('SALARY OF ' || V_EMPLOYEE_ID || ' IS LESS THAN MAXIMUM.');    
    ELSE
        DBMS_OUTPUT.PUT_LINE('SALARY OF ' || V_EMPLOYEE_ID || ' IS MAXIMUM.');
    END IF;
    
EXCEPTION
    WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('EXCEPTION : EMPLOYEE ID NOT FOUND.');
END;
/
