SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
V_MIN NUMBER(10);
V_MAX NUMBER(10);
V_AVG NUMBER(10);

BEGIN
    SELECT MIN(SALARY), MAX(SALARY), AVG(SALARY)
        INTO V_MIN,V_MAX,V_AVG
        FROM EMPLOYEE;
 
        DBMS_OUTPUT.PUT_LINE('MINIMUM SALARY : ' || V_MIN);
        DBMS_OUTPUT.PUT_LINE('AVERAGE SALARY : ' || V_AVG);
        DBMS_OUTPUT.PUT_LINE('MAXIMUM SALARY : ' || V_MAX);
-- EXCEPTION
   
END;
/
