SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := 7950;
V_LAST_NAME EMPLOYEE.LAST_NAME%TYPE;

V_NAME VARCHAR(20) := 'SARA';
V_DATE DATE;

BEGIN

    V_NAME := NVL(V_NAME, 'UNKNOWN');
    V_DATE := NVL(V_DATE, SYSDATE); 

    DBMS_OUTPUT.PUT_LINE(V_NAME||' BORN ON '||V_DATE);

    SELECT LAST_NAME
        INTO V_LAST_NAME
        FROM EMPLOYEE
        WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;
        --7788
        --DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : ' || V_LAST_NAME);

EXCEPTION
    WHEN NO_DATA_FOUND 
        THEN DBMS_OUTPUT.PUT_LINE('EMPLOYEE NAME : ' || V_EMPLOYEE_ID || ' IS NOT FOUND');
    WHEN OTHERS 
        THEN DBMS_OUTPUT.PUT_LINE('EXCEPTION !');

END;
/
