SET SERVEROUTPUT ON

DECLARE
V_LAST_NAME VARCHAR2(15);
V_HIRE_DATE DATE;
V_SALARY NUMBER;

BEGIN
SELECT LAST_NAME,HIRE_DATE,SALARY
    INTO V_LAST_NAME,V_HIRE_DATE,V_SALARY
    FROM EMPLOYEE
    WHERE EMPLOYEE_ID = 7788;

    DBMS_OUTPUT.PUT_LINE('NAME: ' || V_LAST_NAME);
    DBMS_OUTPUT.PUT_LINE('HIRE DATE: ' || to_char(V_HIRE_DATE,'YYYY/MM/DD'));
    DBMS_OUTPUT.PUT_LINE('SALARY: ' || V_SALARY);

-- EXCEPTION

END;
/
