SET SERVEROUTPUT ON

DECLARE
V_ID NUMBER(4) := 5511;
C_ID CONSTANT NUMBER(4) := 2222;

BEGIN
  V_ID := 1234;
--   C_ID := 2231;
  DBMS_OUTPUT.PUT_LINE('ID = ' || V_ID);
  DBMS_OUTPUT.PUT_LINE('ID = ' || C_ID);
END;
/
