SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
CURSOR EMPLOYEE_INFO IS
SELECT EMPLOYEE_ID,LAST_NAME,SALARY
FROM EMPLOYEE WHERE SALARY > (SELECT AVG(SALARY) FROM EMPLOYEE);

BEGIN
  FOR V_ROW IN EMPLOYEE_INFO LOOP
    DBMS_OUTPUT.PUT_LINE('ID :  ' || V_ROW.EMPLOYEE_ID);
    DBMS_OUTPUT.PUT_LINE('NAME :  ' || V_ROW.LAST_NAME);
    DBMS_OUTPUT.PUT_LINE('SALARY :  ' || V_ROW.SALARY);
    DBMS_OUTPUT.PUT_LINE(CHR(13));
  END LOOP;
END;
/