SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &SV_EMPLOYEE_ID;
    V_SALARY EMPLOYEE.SALARY%TYPE;
    V_JOB_ID EMPLOYEE.JOB_ID%TYPE;
BEGIN
    SELECT JOB_ID,SALARY 
        INTO V_JOB_ID,V_SALARY
        FROM EMPLOYEE
        WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

    CASE V_JOB_ID
        WHEN 667 THEN V_SALARY := V_SALARY * 1.05;
        WHEN 672 THEN V_SALARY := V_SALARY * 1.10;
    END CASE;

    UPDATE EMPLOYEE
        SET SALARY = V_SALARY
        WHERE EMPLOYEE_ID = V_EMPLOYEE_ID;

     DBMS_OUTPUT.PUT_LINE('EMPLOYEE : ' || V_EMPLOYEE_ID);
     DBMS_OUTPUT.PUT_LINE('JOB ID : ' || V_JOB_ID);        
     DBMS_OUTPUT.PUT_LINE('SALARY : ' || V_SALARY);        
END;
/

