SET SERVEROUTPUT ON
SET VERIFY OFF
CREATE OR REPLACE PROCEDURE FIND_JOB(I_JOB_ID IN NUMBER, O_FUNCTION OUT VARCHAR2)
AS

BEGIN
    SELECT FUNCTION INTO O_FUNCTION
        FROM JOB
        WHERE JOB_ID = I_JOB_ID;
EXCEPTION
  WHEN OTHERS THEN
    DBMS_OUTPUT.PUT_LINE('JOB ID NOT FOUND');      
END FIND_JOB; 
/