SET SERVEROUTPUT ON
SET VERIFY OFF
    
BEGIN

    DBMS_OUTPUT.PUT_LINE('FUNCTION CALL DEPARTMENT : ' || GET_NAME(10));
   
EXCEPTION
  WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ID NOT FOUND');

END;
/