SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE FUNCTION GET_NAME (I_DEP_ID IN NUMBER) RETURN VARCHAR2
AS
    V_NAME DEPARTMENT.NAME%TYPE;
    
BEGIN
    SELECT NAME
        INTO V_NAME
        FROM DEPARTMENT
        WHERE DEPARTMENT_ID = I_DEP_ID;
        DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID : ' || I_DEP_ID);      
        RETURN V_NAME;

EXCEPTION
  WHEN OTHERS THEN
        DBMS_OUTPUT.PUT_LINE('ID NOT FOUND');
        RETURN NULL;
END GET_NAME;
/