SET SERVEROUTPUT ON
SET VERIFY OFF

CREATE OR REPLACE FUNCTION IS_VALID(I_DEP_ID IN NUMBER) RETURN BOOLEAN
AS 

V_COUNT NUMBER;

BEGIN
    SELECT COUNT(*)
        INTO V_COUNT
        FROM DEPARTMENT
        WHERE DEPARTMENT_ID = I_DEP_ID;

    RETURN 1 = V_COUNT;    
  
EXCEPTION
    WHEN OTHERS THEN
        RETURN FALSE;  
END IS_VALID;
/