SET SERVEROUTPUT ON
SET VERIFY OFF
CREATE OR REPLACE PROCEDURE DISPLAY_EMPLOYEES(I_DEP_ID IN NUMBER)
AS
    CURSOR C_EMPLOYEES IS 
        SELECT LAST_NAME, SALARY
        FROM EMPLOYEE
        WHERE DEPARTMENT_ID = I_DEP_ID;

    V_AVG NUMBER;    

BEGIN
    V_AVG := AVG_SALARY(I_DEP_ID);
    DBMS_OUTPUT.PUT_LINE('AVG SALARY : ' || ROUND(V_AVG,2));
    FOR V_ROW IN C_EMPLOYEES LOOP
        DBMS_OUTPUT.PUT_LINE('LAST NAME : ' || V_ROW.LAST_NAME);
        IF V_ROW.SALARY < V_AVG THEN
            DBMS_OUTPUT.PUT_LINE('THIS SALARY : ' || V_ROW.SALARY || ' IS LESS THAN AVERAGE');
        ELSE
            DBMS_OUTPUT.PUT_LINE('THIS SALARY : ' || V_ROW.SALARY || ' IS GREATER THAN AVERAGE');
        END IF;
    END LOOP;
END DISPLAY_EMPLOYEES; 
/