SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    V_DEPARTMENT_ID DEPARTMENT.DEPARTMENT_ID%TYPE := &SV_DEPARTMENT_ID;
    
BEGIN
    DBMS_OUTPUT.PUT_LINE('MIN SALARY : ' || GET_MIN_SALARY(V_DEPARTMENT_ID));
   
EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('DEPARTMENT ID NOT FOUND');
END;
/
