SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE 

V_LOCATION_ID DEPARTMENT.LOCATION_ID%TYPE  := &SV_LOCATION_ID;

CURSOR C_LOCATION IS 
    SELECT NAME, LOCATION_ID, DEPARTMENT_ID 
    FROM DEPARTMENT
    WHERE LOCATION_ID = V_LOCATION_ID;

BEGIN

    FOR V_ROW IN C_LOCATION LOOP
        DBMS_OUTPUT.PUT_LINE(V_ROW.DEPARTMENT_ID || ' - ' || V_ROW.NAME);
    END LOOP;

EXCEPTION
	WHEN NO_DATA_FOUND THEN
	    DBMS_OUTPUT.PUT_LINE('LOCATION ID NOT FOUND ');
END;
/