SET SERVEROUTPUT ON
SET VERIFY OFF

DECLARE
    V_EMPLOYEE_ID EMPLOYEE.EMPLOYEE_ID%TYPE := &SV_EMPLOYEE_ID;
    V_JOB_TITLE JOB.FUNCTION%TYPE;
    
BEGIN
    DISPLAY_JOB(V_EMPLOYEE_ID,V_JOB_TITLE);
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID: '||V_EMPLOYEE_ID);
        DBMS_OUTPUT.PUT_LINE('JOB TITLE: '||V_JOB_TITLE);

END;
/