SET SERVEROUTPUT ON
SET VERIFY OFF
CREATE OR REPLACE PROCEDURE DISPLAY_JOB(I_EMP_ID IN NUMBER, O_NAME OUT VARCHAR2) 
AS

BEGIN
    SELECT JOB.FUNCTION
        INTO O_NAME
        FROM EMPLOYEE JOIN JOB
        USING(JOB_ID)
        WHERE EMPLOYEE_ID = I_EMP_ID;

EXCEPTION
  WHEN NO_DATA_FOUND THEN
        DBMS_OUTPUT.PUT_LINE('EMPLOYEE ID NOT FOUND');

END DISPLAY_JOB; 
/